"""Gitignore management for leakfix - audit and add security patterns."""

from __future__ import annotations

import fnmatch
from pathlib import Path

from leakfix.utils import get_repo_root, is_git_repo


# Required security patterns for .gitignore
REQUIRED_PATTERNS = [
    ".env",
    ".env.*",
    ".env.bak",
    ".env.local",
    ".env.production",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
    "*.cert",
    "*.p8",
    "*secret*",
    "*credential*",
    "*password*",
    "firebase*.json",
    "*adminsdk*.json",
    "*service-account*.json",
    ".aws/credentials",
    ".aws/config",
    "*.jks",
    "*.keystore",
    "*.mobileprovision",
]


class GitignoreManager:
    """Manage .gitignore for secret-related patterns."""

    def __init__(self, source: Path | str | None = None):
        self.source = Path(source or ".").resolve()
        self.repo_root = get_repo_root(self.source) or self.source
        self.gitignore_path = self.repo_root / ".gitignore"

    def audit(self) -> dict:
        """Check for missing patterns and add them. Returns audit result."""
        missing = self._get_missing_patterns(self._read_gitignore())
        if missing:
            self._add_patterns(missing)
        return {
            "missing": missing,
            "added": missing,
            "path": str(self.gitignore_path),
        }

    def generate(self) -> Path:
        """Create comprehensive security-focused .gitignore from scratch."""
        patterns = self._get_required_patterns()
        content = "# leakfix security-focused .gitignore\n# Generated by: leakfix gitignore --generate\n\n"
        content += "\n".join(patterns) + "\n"
        self.gitignore_path.write_text(content, encoding="utf-8")
        return self.gitignore_path

    def check(self) -> dict:
        """Just report missing patterns, don't modify."""
        content = self._read_gitignore()
        missing = self._get_missing_patterns(content)
        return {
            "missing": missing,
            "path": str(self.gitignore_path),
            "exists": self.gitignore_path.exists(),
        }

    def _get_required_patterns(self) -> list[str]:
        """Return list of required security patterns."""
        return list(REQUIRED_PATTERNS)

    def _read_gitignore(self) -> str:
        """Read current .gitignore content."""
        if not self.gitignore_path.exists():
            return ""
        return self.gitignore_path.read_text(encoding="utf-8")

    def _get_missing_patterns(self, gitignore_content: str) -> list[str]:
        """Find which required patterns are missing from .gitignore."""
        lines = [line.strip() for line in gitignore_content.splitlines()]
        existing = set()
        for line in lines:
            if not line or line.startswith("#"):
                continue
            # Normalize: strip comments at end
            pat = line.split("#")[0].strip()
            if pat:
                existing.add(pat)
                # Also add pattern without leading/trailing
                existing.add(pat.rstrip("/"))

        missing = []
        for req in self._get_required_patterns():
            if not self._pattern_covered(req, existing):
                missing.append(req)
        return missing

    def _pattern_covered(self, required: str, existing: set[str]) -> bool:
        """Check if required pattern is covered by any existing pattern."""
        req_lower = required.lower()
        for ex in existing:
            ex_lower = ex.lower()
            if ex_lower == req_lower:
                return True
            # .env* covers .env, .env.local, .env.bak, etc.
            if ex_lower == ".env*" and req_lower.startswith(".env"):
                return True
            # .env.* covers .env.local, .env.production
            if ex_lower == ".env.*" and req_lower.startswith(".env."):
                return True
            # *adminsdk* covers *adminsdk*.json
            if "*adminsdk*" in ex_lower and "adminsdk" in req_lower:
                return True
            # *service-account* covers *service-account*.json
            if "*service-account*" in ex_lower and "service-account" in req_lower:
                return True
        return False

    def _add_patterns(self, patterns: list[str]) -> None:
        """Add missing patterns to .gitignore."""
        content = self._read_gitignore()
        if content and not content.endswith("\n"):
            content += "\n"
        if patterns:
            add_block = "\n# leakfix: security patterns\n" + "\n".join(patterns) + "\n"
            if "# leakfix: security patterns" not in content:
                content += add_block
            else:
                # Append new patterns after existing block
                for p in patterns:
                    if p not in content:
                        content += p + "\n"
        self.gitignore_path.write_text(content, encoding="utf-8")
